name: 'Demo Workflow'
on:
 push:
  branches: [master, vara]
 pull_request:
  types: [closed]
  branches: [master, vara]
 schedule: 
  - cron: '* * * * *'

jobs:

  varalakshmi:
    name: 'varalakshmi job'
    runs-on : ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: print Runner Hostname
      run: hostname
      shell: bash
    - name: print Runner IP address
      run: curl -sL https://ipconfig.io
      shell: bash
    - name: Setup Terraform with Specified version on runner
      uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: 1.6.6
    - name: check terraform version
      run: terraform version
      shell: bash         


  vedanshi:
    name: 'vedanshi job'
    needs: 'varalakshmi job'
    runs-on : ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: print Runner Hostname
      run: hostname
      shell: bash
    - name: print Runner IP address
      run: curl -sL https://ipconfig.io
      shell: bash
    - name: Setup Terraform with Specified version on runner
      uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: 1.6.6


  vishwak:
    name: 'vishwak job'
    needs: 'vedanshi job'    
    runs-on : ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: print Runner Hostname
      run: hostname
      shell: bash
    - name: print Runner IP address
      run: curl -sL https://ipconfig.io
      shell: bash
    - name: Setup Terraform with Specified version on runner
      uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: 1.6.6

