#This is a demo workflow file to test github actions
name: 'Demo Workflow'
  on:
  - push
  - pull_request:
    - closed
  - schedule: 
    - cron: '* * * * *'

  jobs:

    varalakshmi:
      name: 'varalakshmi job'
      runs-on : ubuntu-latest
      defaults:
        run:
          shell: bash
      steps:
      - name: ping www.googl.com
        run: ping -c 3 www.google.com
        shell: bash
      - name: ping www.yahoo.com    
        run: ping -c 3 www.yahoo.com
        shell: bash

  #vedanshi:

  #vishwak:
