#This is a demo workflow file to test github actions
name: 'Demo Workflow'
on:
 push:
 pull_request:
  types: [closed]
 schedule: 
  - cron: '* * * * *'
#
jobs:

  varalakshmi:
    name: 'varalakshmi job'
    runs-on : ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: print Runner Hostname
      run: hostname
      shell: bash
    - name: print Runner IP address
      run: curl -sL https://ipconfig.io
      shell: bash

  #vedanshi:

  #vishwak:
