name: 'vamsi Workflow'
on:
  workflow_dispatch:
   inputs:
    TERRAFORM_DESTROY:
      description: 'Shall we Run Terraform Destroy ?'
      required: true
      defautlt: 'DONT DESTORY'
      type: choice
      options:
      - DONT_DESTROY
      - DESTROY
    ENVIRONMENT:
      description: 'Select which Subscription You Wan to Deploy?'  
      required: true
      default: 'Development'
      type: choice
      options:
      - free_trail
      
env:
  TERRAFORM_DES: "YES"
  ENVIRONMENT: "Development"
#  ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
  ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
  ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
  ACTIONS_STEP_DEBUG: true

jobs:

  varalakshmi:
    name: 'varalakshmi job'
    runs-on : ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: print Runner Hostname
      run: hostname
      shell: bash
    - name: print Runner IP address
      run: curl -sL https://ipconfig.io
      shell: bash
    - name: list Repo files
      shell: bash           
      run: |
       ls -al
       pwd
       free      
    - name: Setup Terraform with Specified version on runner
      uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: 1.6.6
    - name: check terraform version
      run: terraform version
      shell: bash  

    - name: check Env version
      shell: bash     
      run: |
       echo
       echo ${{github.event.inputs.ENVIRONMENT}}    
       echo ${{github.event.inputs.TERRAFORM_DESTROY}}
       export ARM_SUBSCRIPTION_ID ='3cf019f3-f4ce-4a58-9267-7ea16b45d46c'
       terraform init && terraform validate && terraform fmt




  vedanshi:
    name: 'vedanshi job'

    runs-on : ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: print Runner Hostname
      run: hostname
      shell: bash
    - name: print Runner IP address
      run: curl -sL https://ipconfig.io
      shell: bash
    - name: Setup Terraform with Specified version on runner
      uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: 1.6.6


  vishwak:
    name: 'vishwak job'
      
    runs-on : ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: print Runner Hostname
      run: hostname
      shell: bash
    - name: print Runner IP address
      run: curl -sL https://ipconfig.io
      shell: bash
    - name: Setup Terraform with Specified version on runner
      uses: hashicorp/setup-terraform@v2
      with:
         terraform_version: 1.6.6

